### ISSUE TITLE
Chrome Dev Tools createSession method not working

### ISSUE THREAD

**Issue by sethutks** [SeleniumHQ/seleniumhq.github.io#735] opened 2021-08-06 11:29 UTC
To Reproduce:

Chrome Browser Version: 92
Selenium Version: 4.0.0-beta-4

**Code Reference**: https://www.selenium.dev/documentation/en/support_packages/chrome_devtools/
I tried the code piece from Selenium dev and it is not working. 
ChromeDriver driver = new ChromeDriver();
DevTools devTools = driver.getDevTools();
devTools.createSession();

createSession method returns exception. Stack trace attached for reference

java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Void() accessible: module java.base does not "opens java.lang" to unnamed module @66f8087e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at org.openqa.selenium.json.InstanceCoercer.getConstructor(InstanceCoercer.java:155)
	at org.openqa.selenium.json.InstanceCoercer.test(InstanceCoercer.java:48)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$4(JsonTypeCoercer.java:134)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openqa.selenium.json.JsonTypeCoercer.buildCoercer(JsonTypeCoercer.java:135)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:124)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:289)
	at org.openqa.selenium.devtools.Command.lambda$new$0(Command.java:41)
	at org.openqa.selenium.devtools.Connection.lambda$send$1(Connection.java:109)
	at org.openqa.selenium.devtools.Connection$NamedConsumer.accept(Connection.java:92)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:218)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

Aug 06, 2021 4:47:56 PM org.openqa.selenium.devtools.Connection lambda$send$1
WARNING: Unable to map result for Log.clear
java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Void() accessible: module java.base does not "opens java.lang" to unnamed module @66f8087e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at org.openqa.selenium.json.InstanceCoercer.getConstructor(InstanceCoercer.java:155)
	at org.openqa.selenium.json.InstanceCoercer.test(InstanceCoercer.java:48)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$4(JsonTypeCoercer.java:134)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openqa.selenium.json.JsonTypeCoercer.buildCoercer(JsonTypeCoercer.java:135)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:124)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:289)
	at org.openqa.selenium.devtools.Command.lambda$new$0(Command.java:41)
	at org.openqa.selenium.devtools.Connection.lambda$send$1(Connection.java:109)
	at org.openqa.selenium.devtools.Connection$NamedConsumer.accept(Connection.java:92)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:218)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Void() accessible: module java.base does not "opens java.lang" to unnamed module @66f8087e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at org.openqa.selenium.json.InstanceCoercer.getConstructor(InstanceCoercer.java:155)
	at org.openqa.selenium.json.InstanceCoercer.test(InstanceCoercer.java:48)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$4(JsonTypeCoercer.java:134)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openqa.selenium.json.JsonTypeCoercer.buildCoercer(JsonTypeCoercer.java:135)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:124)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:289)
	at org.openqa.selenium.devtools.Command.lambda$new$0(Command.java:41)
	at org.openqa.selenium.devtools.Connection.lambda$send$1(Connection.java:109)
	at org.openqa.selenium.devtools.Connection$NamedConsumer.accept(Connection.java:92)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:218)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Exception in thread "main" org.openqa.selenium.devtools.DevToolsException: Unable to make private java.lang.Void() accessible: module java.base does not "opens java.lang" to unnamed module @66f8087e
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'ADFL-1312', ip: '192.168.68.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: DevTools Connection
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:125)
	at com.adf.cdt.network.TraceAPI.main(TraceAPI.java:18)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Void() accessible: module java.base does not "opens java.lang" to unnamed module @66f8087e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at org.openqa.selenium.json.InstanceCoercer.getConstructor(InstanceCoercer.java:155)
	at org.openqa.selenium.json.InstanceCoercer.test(InstanceCoercer.java:48)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$4(JsonTypeCoercer.java:134)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openqa.selenium.json.JsonTypeCoercer.buildCoercer(JsonTypeCoercer.java:135)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:124)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:289)
	at org.openqa.selenium.devtools.Command.lambda$new$0(Command.java:41)
	at org.openqa.selenium.devtools.Connection.lambda$send$1(Connection.java:109)
	at org.openqa.selenium.devtools.Connection$NamedConsumer.accept(Connection.java:92)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:218)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Aug 06, 2021 4:47:56 PM org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"id":3,"result":{},"sessionId":"1C1056BB79B0836F5C5B7F4C9FC34710"}
org.openqa.selenium.json.JsonException: Expected to read a NAME but instead have: START_MAP. Last 17 characters read: {"id":3,"result":
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'ADFL-1312', ip: '192.168.68.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:300)
	at org.openqa.selenium.json.JsonInput.nextName(JsonInput.java:136)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:216)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: Expected to read a NAME but instead have: START_MAP. Last 17 characters read: {"id":3,"result":
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'ADFL-1312', ip: '192.168.68.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.openqa.selenium.json.JsonException: Expected to read a NAME but instead have: START_MAP. Last 17 characters read: {"id":3,"result":
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'ADFL-1312', ip: '192.168.68.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:300)
	at org.openqa.selenium.json.JsonInput.nextName(JsonInput.java:136)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:216)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	... 3 more
Aug 06, 2021 4:47:56 PM org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"id":4,"result":{},"sessionId":"1C1056BB79B0836F5C5B7F4C9FC34710"}
org.openqa.selenium.json.JsonException: Expected to read a NAME but instead have: START_MAP. Last 17 characters read: {"id":4,"result":
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'ADFL-1312', ip: '192.168.68.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:300)
	at org.openqa.selenium.json.JsonInput.nextName(JsonInput.java:136)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:216)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: Expected to read a NAME but instead have: START_MAP. Last 17 characters read: {"id":4,"result":
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'ADFL-1312', ip: '192.168.68.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.openqa.selenium.json.JsonException: Expected to read a NAME but instead have: START_MAP. Last 17 characters read: {"id":4,"result":
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'ADFL-1312', ip: '192.168.68.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:300)
	at org.openqa.selenium.json.JsonInput.nextName(JsonInput.java:136)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:216)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
	... 3 more

**Comment by diemol** [comment] 2021-08-06 11:41
This is a duplicate of https://github.com/SeleniumHQ/selenium/issues/9676, which was fixed in `trunk` and will be available in the next release. For now, if you use Java 11 it will work.

**Closed as completed by diemol** 2021-08-06 11:41 UTC

**Comment by sethutks** [comment] 2021-08-06 11:47
Thanks diemol
