### ISSUE TITLE
Some pages completely freeze the browser tab on Firefox and Chromium

### ISSUE THREAD

**Issue by o-alquimista** [SeleniumHQ/seleniumhq.github.io#751] opened 2021-08-24 23:18 UTC
### Description
The scripts in some pages are causing the browser tab to freeze.

The CPU usage goes high and the browser shows a warning that the page is slowing my computer down. Nothing shows on the browser console, so I can't provide any useful logs.

### To reproduce
1. Go to https://www.selenium.dev/documentation/webdriver/
2. Click on "browser manipulation" or "locating elements". It freezes at this point, most of the time.
3. If the page has loaded successfully, click on any of the language tabs (e.g. Python)

The "waits" page loads fine, though.

### System info
Mozilla Firefox 91.0.1
Chromium 92.0.4515.159 snap
Ubuntu 21.04 (wayland session, GNOME desktop)

**Comment by wujr5** [comment] 2021-08-25 02:23
I have the same problem.

**Comment by diemol** [comment] 2021-08-25 05:06
This is a duplicate of #750

**Closed as completed** 2021-08-25 05:06 UTC
