### ISSUE TITLE
When adding Selenium.WebDriver to C# project using VSCode, the project doesn't compile

### ISSUE THREAD

**Issue by tarekahf** [SeleniumHQ/seleniumhq.github.io#952] opened 2022-02-10 16:19 UTC
### What happened?

I was following the steps here:

https://www.fleekitsolutions.com/use-selenium-c-visual-studio-code/

To use Selenium 4 with vs code. I installed .NET 5 and .NET 6 SDK. 

I created the sample Hello World Project using `dotnet new console` and tried to import the Selenium.WebDriver package using NuGet, and run `dotnet restore`, I get the following error:

`error NU1100: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for 'net6.0'.`

![vscode CS Selenium error](https://user-images.githubusercontent.com/20842027/153449793-cc383d65-872c-4162-810d-5bb4629e2ee3.png)

### How can we reproduce the issue?

```shell
- Open vscode
- Switch to .NET 5 to verify or use .NET 6 (the default and latest one installed)
`dotnet new globaljson --sdk-version 5.0.405 --force`
- Create sample dotnet project using `dotnet new console`
- Run the project ==> is is good
- Import Selnium.WebDriver using NuGet Add Package (Ctrl-Shift-P)
- Run `dotnet restore` you will get this error:
`error NU1100: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for 'net6.0'`
```

### Relevant log output
The OmniSharp server output will display the following:
```shell
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj'.
c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj
c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj(0,0): Error: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for '.NETFramework,Version=v4.8'.
c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj(0,0): Error: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for '.NETFramework,Version=v4.8/win7-x86'.

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FirsProj
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        FirsProj: Did not find 'Selenium.WebDriver' in lock file.
```

### Operating System

Windows 10 Enterprise

### Selenium version

C# with .NET 6 and VSCode

### What are the browser(s) and version(s) where you see this issue?

98.0.4758.82

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98.0.4758.82

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment] 2022-02-10 18:09
Duplicate of https://github.com/SeleniumHQ/selenium/issues/10354

**Closed as completed by diemol** 2022-02-10 18:09 UTC
