### ISSUE TITLE
No Health Check URL for Nodes.

### ISSUE THREAD

**Issue by burninmedia** [SeleniumHQ/seleniumhq.github.io#330] opened 2020-03-17 21:15 UTC
## 🐛 Bug Report

Trying to run any selenium node containers in a k8s cluster you can get into a state where the node is not accepting any more tests. Normally this is what a health endpoint is for, helping us know when the node is not working.

## To Reproduce

Try to use the hub health check url on a node.
http://$HOST:$PORT/wd/hub/status

Tell us the detailed steps to reproduce it:
Try using curl on this URL on a node and you get connection refused. 

## Expected behavior

What do you expect to happen? How should have it worked?
I expected to get back a JSON response just like the hub would provide.

## Environment

Your grid-node containers are what I am using.
https://hub.docker.com/u/selenium

**Comment by diemol** [comment] 2020-03-18 07:06
Duplicate of https://github.com/SeleniumHQ/selenium/issues/8117

**Closed by diemol** 2020-03-18 07:06 UTC
Labels: needs-triaging
