### ISSUE TITLE
Broken links in Java API documentation search bar

### ISSUE THREAD

**Issue by vedangnaik** [SeleniumHQ/seleniumhq.github.io#729] opened 2021-07-22 12:01 UTC
## 🐛 Bug Report

The search box in the Java API documentation goes to a 404 page when searching for `ChromeOptions` and clicking the autocomplete link for the same. This appears to be an issue when searching for any Type or Member in general.

## To Reproduce

1. Go to https://www.selenium.dev/selenium/docs/api/java/overview-summary.html .
2. Type `ChromeOptions` in the search box in the top-right. Click the autocomplete link for `org.openqa.selenium.chrome.ChromeOptions`.

This goes to the following 404 page at https://www.selenium.dev/selenium/docs/api/java/undefined/org/openqa/selenium/chrome/ChromeOptions.html :
![image](https://user-images.githubusercontent.com/25436568/126635248-da100c09-0242-4e4b-bf68-c243fedab1c1.png)

## Expected behavior

Expected to go to the ChromeOptions page at https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/chrome/ChromeOptions.html .

## Environment

* OS: Windows 10 Home, Version 21H1 (OS Build 19043.1110)
* Browser: Google Chrome
* Browser version: Version 91.0.4472.164 (Official Build) (64-bit)

**Comment by vedangnaik** [comment] 2021-07-22 12:05
The culprit appears to be this 'undefined' in the link:  `www.selenium.dev/selenium/docs/api/java/**undefined**/org/openqa/selenium/chrome/ChromeOptions.html` .
Removing it leads to the correct page in every instance I've tested. I'd be happy to investigate this further and submit a fix.

**Comment by vedangnaik** [comment] 2021-10-22 03:42
Hi, I've not really had time since I opened this issue to work on it. In case my previous comment is preventing someone else from working on this: please consider it open. I am unlikely to have time to look into it.

**Comment by csankhala** [comment] 2021-12-03 11:28
@diemol  This issue is marked duplicate of https://github.com/SeleniumHQ/selenium/issues/9766 and that is closed.

Can we mark this as closed?

**Comment by diemol** [comment] 2021-12-03 13:21
I believe this is not fixed yet, which is why we have not closed it.

**Closed as completed** 2022-04-07 09:31 UTC
